export const developerSkills = [
  "JavaScript frameworks",
  "React.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "Ember.js",
  "jQuery",
  "Bootstrap",
  "Material-UI",
  "Express.js",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Laravel",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "GraphQL",
  "SOAP",
  "Git",
  "SVN",
  "iOS development",
  "Swift",
  "Objective-C",
  "Xcode",
  "Android development",
  "Java",
  "Kotlin",
  "Android Studio",
  "React Native",
  "Flutter",
  "Xamarin",
  "AWS",
  "EC2",
  "S3",
  "Lambda",
  "DynamoDB",
  "Azure",
  "VMs",
  "Storage Accounts",
  "Functions",
  "Cosmos DB",
  "Google Cloud",
  "Compute Engine",
  "Storage",
  "Functions",
  "Bigtable",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "GitLab CI",
  "CircleCI",
  "Prometheus",
  "Grafana",
  "ELK stack",
  "Ansible",
  "Puppet",
  "Chef",
  "NumPy",
  "pandas",
  "scikit-learn",
  "TensorFlow",
  "PyTorch",
  "dplyr",
  "ggplot2",
  "caret",
  "SPSS",
  "R",
  "Matplotlib",
  "Seaborn",
  "Plotly",
  "MySQL",
  "PostgreSQL",
  "Oracle",
  "MongoDB",
  "Cassandra",
  "Couchbase",
  "InfluxDB",
  "TimescaleDB",
  "JUnit",
  "NUnit",
  "pytest",
  "Selenium",
  "Cypress",
  "JMeter",
  "Gatling",
  "OWASP ZAP",
  "Burp Suite",
  "Scrum",
  "Kanban",
  "Jira",
  "Asana",
  "Markdown",
  "Sphinx",
  "Communication",
  "Problem-solving",
  "Team collaboration",
];

export const universities = [
  "Massachusetts Institute of Technology",
  "Harvard University",
  "Stanford University",
  "University of California, Berkeley",
  "Cornell University",
  "University of Chicago",
  "Princeton University",
  "Johns Hopkins University",
  "Columbia University",
  "University of Michigan-Ann Arbor",
  "Northwestern University",
  "Carnegie Mellon University",
  "Duke University",
  "University of Texas at Austin",
  "University of Illinois at Urbana-Champaign",
  "University of Washington",
  "Brown University",
  "Pennsylvania State University",
  "Boston University",
  "Georgia Institute of Technology",
  "University of Wisconsin-Madison",
  "University of Southern California",
  "Rice University",
  "Michigan State University",
  "Texas A&M University",
  "University of North Carolina at Chapel Hill",
  "Washington University in St. Louis",
  "Emory University",
  "University of Minnesota Twin Cities",
  "Ohio State University",
  "University of Florida",
  "University of Maryland, College Park",
  "University of Rochester",
  "Vanderbilt University",
  "Case Western Reserve University",
  "University of Massachusetts Amherst",
  "University of Pittsburgh",
  "University of Virginia",
  "Georgetown University",
  "University of Colorado Boulder",
  "Tufts University",
  "Indiana University Bloomington",
  "University of Nebraska - Lincoln",
  "American University",
  "Arizona State University",
];

export const devRoles = [
  "Software Engineer",
  "Senior Software Engineer",
  "Lead Software Engineer",
  "Principal Software Engineer",
  "Architect",
  "Senior Architect",
  "Cloud Architect",
  "DevOps Engineer",
  "Solutions Architect",
  "Backend Developer",
  "Frontend Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "Data Scientist",
  "Machine Learning Engineer",
  "DevSecOps Engineer",
  "Site Reliability Engineer",
  "Quality Assurance (QA) Engineer",
  "Test Automation Engineer",
  "UX/UI Designer",
  "Product Manager",
  "Technical Lead",
  "Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "CTO",
  "Software Developer",
  "Junior Software Developer",
  "Intermediate Software Developer",
  "Senior Software Developer",
  "Lead Developer",
  "Staff Software Engineer",
  "Senior Backend Developer",
  "Senior Frontend Developer",
  "Senior Full Stack Developer",
  "Senior Mobile App Developer",
  "Senior Data Scientist",
  "Senior Machine Learning Engineer",
  "Senior DevSecOps Engineer",
  "Senior Site Reliability Engineer",
  "Senior QA Engineer",
  "Senior UX/UI Designer",
  "Senior Technical Lead",
  "Senior Engineering Manager",
  "Senior Director of Engineering",
  "Senior VP of Engineering",
  "Senior CTO",
];

export const developerTeamNames = [
  "Code Crusaders",
  "Byte Bandits",
  "Pixel Pioneers",
  "Algorithm Avengers",
  "Tech Titans",
  "Cybernetic Cowboys",
  "Quantum Quillers",
  "Digital Dynamos",
  "Binary Bandits",
  "Syntax Sorcerers",
  "Logic Legends",
  "Circuit Crusaders",
  "Memory Masters",
  "Processor Pioneers",
  "Network Ninjas",
  "Cloud Commandos",
  "AI Architects",
  "Robot Renegades",
  "Data Detectives",
  "Cybersecurity Sentinels",
  "DevOps Daredevils",
  "FullStack Fanatics",
  "Mobile Mavericks",
  "Web Wizards",
  "Game Geniuses",
  "IoT Innovators",
  "Blockchain Builders",
  "Machine Learning Maestros",
  "Quantum Computing Questers",
];
